name: Lint

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
          node-version-file: ".tool-versions"
      - name: Install dependencies
        run: pnpm install
      - name: Lint with textlint
        if: github.event_name == 'pull_request'
        uses: tsuyoshicho/action-textlint@v3
        with:
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm
          reporter: github-pr-review
          textlint_flags: "{articles/books}/*.md"
      - name: Lint with textlint
        if: github.event_name == 'push'
        uses: tsuyoshicho/action-textlint@v3
        with:
          fail_on_error: true
          filter_mode: nofilter
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm
          reporter: github-check
          textlint_flags: "{articles/books}/*.md"
